### ISSUE TITLE
import error, file not found

### ISSUE THREAD

**Issue by ZacDiggum** [hunse/pyopencl_blas#1]
Hey there,

I managed to build and install the module, got my blas.so, installed with --user flag, no errors. When trying to import pyopencl_blas I get this:
ImportError: libclBLAS.so.2: cannot open shared object file: No such file or directory
libclBLAS.so.2 is in a path I pointed to in setup.py. I also added a file to ld.so.conf.d containing the path. Are there any naming rules for the file in ld.so.conf.d?
Could I install the module without the --user flag? I'm on Linux Mint 17.2.
Thanks in advance...

**Comment by ZacDiggum** [comment]
Never mind, I changed the file name to libclBLAS.so.2.conf and now it works. My mistake, stupid me...

**Comment by hunse** [comment]
The naming rule is that files have to end in `.conf`. I've added a clarification to the README. Thanks!
